In [1]:
subjects = ['Math', 'Physics', 'English', 'Filipino']
for subs in subjects:
  print(subs)

Math
Physics
English
Filipino


In [2]:
print(subjects[2])

English


In [3]:
subjects[1:]

['Physics', 'English', 'Filipino']

In [4]:
scientist = {'Name': 'Alan Turing', 'Field': 'Mathematics'}
print('Name: ', scientist['Name'])

Name:  Alan Turing


In [6]:
scientist['Field'] = 'Mathematics, Computer Science, Biology'
print(scientist)

{'Name': 'Alan Turing', 'Field': 'Mathematics, Computer Science, Biology'}


In [7]:
scientist.keys()

dict_keys(['Name', 'Field'])

In [8]:
scientist.values()

dict_values(['Alan Turing', 'Mathematics, Computer Science, Biology'])

In [10]:
if 'Mathematics' in subjects:
  print('Mathematics in subject')
elif 'Math' in subjects:
  print('Yes, girl!')
else:
  print('No subject')

Yes, girl!


In [14]:
value = 0

while True:
  print('Hello!', end=' ')
  if value == 3:
    break
  else:
    value +=1

Hello! Hello! Hello! Hello! 

In [25]:
import numpy as np


x = np.array([1, 2, 3]) #vector
print(x)

[1 2 3]


In [16]:
a = np.zeros((2, 2))
print(a)

[[0. 0.]
 [0. 0.]]


In [17]:
b = np.ones((2, 2))
print(b)

[[1. 1.]
 [1. 1.]]


In [20]:
quo = a/b
print(quo)

[[0. 0.]
 [0. 0.]]


In [26]:
from numpy import random
c = np.random.randit(10, size = (5))
d = np.random.randit(10, size = (4))
print(c)

AttributeError: ignored

In [27]:
x = np.array([1, 2, 3])
y = np.array([4, 5, 6])
np.add(x, y)


array([5, 7, 9])

In [28]:
np.divide(x,y)

array([0.25, 0.4 , 0.5 ])

In [29]:
np.subtract(x,y)

array([-3, -3, -3])

In [30]:
np.multiply(x,y)

array([ 4, 10, 18])

In [31]:
np.dot(x,y)
x.dot(y)
y.dot(x)

32

In [32]:
np.argmax(x)
np.argmax(y)

2

In [33]:
for number in x:
  print(number, end=' ')

1 2 3 

In [34]:
print(x > y)

[False False False]


In [35]:
print(x == y)

[False False False]


In [36]:
print(np.equal(x,y))

[False False False]


In [37]:
print(x.dtype)

int64


In [38]:
print(np.sqrt(x))

[1.         1.41421356 1.73205081]


In [40]:
print(np.sum(x))

6


In [41]:
print(np.sum(x, axis=0))

6


In [43]:
z = np.array([[1,2], [3,4]])

print(np.sum(z, axis=1))

[3 7]


In [116]:
#--------------------------------------------------------EXERCISE------------------------------------------------------------------------
A = np.array([[22, 5, 16, 9],[13, 20, 19, 0], [5, 9, 1, 16], [27, 13, 15, 19]])
print('A = ', A)
B = np.array([[10, 5, 20, 20], [5, 21, 22, 27], [26, 19, 22, 3], [27, 8, 18, 7]])
print('B = ', B)
C = np.array([24, 3, 17, 7, 11, 2, 21, 2, 24, 18, 3, 11, 14, 25, 2, 20])
print('C = ', C)
D = np.array([3, 15, 24, 22, 19, 24, 4, 29, 6, 3, 20, 1, 11, 25, 26, 6])
print('D = ', D)


A =  [[22  5 16  9]
 [13 20 19  0]
 [ 5  9  1 16]
 [27 13 15 19]]
B =  [[10  5 20 20]
 [ 5 21 22 27]
 [26 19 22  3]
 [27  8 18  7]]
C =  [24  3 17  7 11  2 21  2 24 18  3 11 14 25  2 20]
D =  [ 3 15 24 22 19 24  4 29  6  3 20  1 11 25 26  6]


In [117]:

#1.
np.add(A,B)


array([[32, 10, 36, 29],
       [18, 41, 41, 27],
       [31, 28, 23, 19],
       [54, 21, 33, 26]])

In [110]:
#2.
np.subtract(A,B)


array([[ 12,   0,  -4, -11],
       [  8,  -1,  -3, -27],
       [-21, -10, -21,  13],
       [  0,   5,  -3,  12]])

In [111]:
#3.
np.multiply(A,B)


array([[220,  25, 320, 180],
       [ 65, 420, 418,   0],
       [130, 171,  22,  48],
       [729, 104, 270, 133]])

In [112]:
#4.
np.matmul(A,B)

array([[ 904,  591, 1064,  686],
       [ 724,  846, 1118,  857],
       [ 553,  361,  608,  458],
       [1238,  845, 1498, 1069]])

In [98]:
#5.
cdSum = C + D
print(cdSum)

[27 18 41 29 30 26 25 31 30 21 23 12 25 50 28 26]


In [97]:
#6
cdSub = C - D
print(cdSub)

[ 21 -12  -7 -15  -8 -22  17 -27  18  15 -17  10   3   0 -24  14]


In [99]:
#7
cdProd = C * D
print(cdProd)

[ 72  45 408 154 209  48  84  58 144  54  60  11 154 625  52 120]


In [114]:
#8
cdDot = np.dot(C,D)
print(cdDot)

  

2298


In [101]:
#9
aPlus = A + 10
print(aPlus)

[[32 15 26 19]
 [23 30 29 10]
 [15 19 11 26]
 [37 23 25 29]]


In [102]:
#10
bPlus = B + 10
print(bPlus)

[[20 15 30 30]
 [15 31 32 37]
 [36 29 32 13]
 [37 18 28 17]]


In [104]:
#11
cPlus = C + 15
print(cPlus)

[39 18 32 22 26 17 36 17 39 33 18 26 29 40 17 35]


In [105]:
#12
dPlus = D + 15
print(dPlus)

[18 30 39 37 34 39 19 44 21 18 35 16 26 40 41 21]


In [106]:
#13
e = (2 * A) + (2 * B)
print(e)

[[ 64  20  72  58]
 [ 36  82  82  54]
 [ 62  56  46  38]
 [108  42  66  52]]


In [107]:
#14
f = (A + B) * 3
print(f)

[[ 96  30 108  87]
 [ 54 123 123  81]
 [ 93  84  69  57]
 [162  63  99  78]]


In [108]:
#15
g = (A - B + A - B + B) * 4
print(g)

[[ 136   20   48   -8]
 [  84   76   64 -108]
 [ -64   -4  -80  116]
 [ 108   72   48  124]]


In [0]:
#-----------------------------------ENd EXERCISE-----------------------------------